#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 10 22:12:04 AST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=MakeUp-UltraFast-9.5d.zip
enableShaders=false
