#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 06 16:14:03 AST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=MakeUp-UltraFast-9.5d.zip
enableShaders=false
