#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 29 18:06:27 PDT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Better MC - Medium
enableShaders=false
